
LocationPath: "./database/TUSS-Instance-Generator/scenario_settings/setting_seed/location_solver.json"
ScenarioPath: "./database/TUSS-Instance-Generator/scenario_settings/setting_seed/scenario_solver.json"
PlanPath: "./database/TUSS-Instance-Generator/scenario_settings/setting_seed/plan.json"
Mode: "DeepLook" #Standard or DeepLook


TabuSearch:
  Iterations: 40
  IterationsUntilReset: 100
  TabuListLength: 16
  Bias: 0.5
  SuppressConsoleOutput: false

SimulatedAnnealing:
  MaxDuration: 3600
  StopWhenFeasible: true
  IterationsUntilReset: 150000
  T: 15
  A: 0.97
  Q: 2000
  Reset: 2000
  Bias: 0.2
  SuppressConsoleOutput: false
  IintensifyOnImprovement: false
DeepLook:
  TestCases: 0
  MaxTest: 100
  EvaluatorInput:
    Path: "/workspace/robust-rail-evaluator/build/TORS" #../../C++/hello"
    Mode: "EVAL_AND_STORE" #EVAL_AND_STORE or EVAL
    PathLocation: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_seed"
    PathScenario: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_seed/scenario_evaluator.json"
    PathPlan: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_seed/plan.json"
    PlanType: "Solver"
    DepartureDelay: "0"
  ConversionAndStorage:  
    PathEvalResult: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_seed/Evaluation_Results.txt"
    PathScenarioEval: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_seed"
  DeterministicPlanning:
    LookForSeed: false # looking for a seed, so the seed value is modified, if TestCases is 0 and LookForSeed is true the scenario is not modified only the seed value is modified in the
    DisplaySeed: true
    Seed: 11298