
LocationPath: "./database/TUSS-Instance-Generator/scenario_settings/setting_known_problems/setting_invalid_endmove/location_solver.json"
ScenarioPath: "./database/TUSS-Instance-Generator/scenario_settings/setting_known_problems/setting_invalid_endmove/scenario_solver.json"
PlanPath: "./database/TUSS-Instance-Generator/scenario_settings/setting_known_problems/setting_invalid_endmove/plan.json"
Mode: "DeepLook" #Standard or DeepLook


TabuSearch:
  Iterations: 40
  IterationsUntilReset: 100
  TabuListLength: 16
  Bias: 0.5
  SuppressConsoleOutput: false

SimulatedAnnealing:
  MaxDuration: 3600
  StopWhenFeasible: true
  IterationsUntilReset: 150000
  T: 15
  A: 0.97
  Q: 2000
  Reset: 2000
  Bias: 0.2
  SuppressConsoleOutput: false
  IintensifyOnImprovement: false
DeepLook:
  TestCases: 3
  MaxTest: 10
  EvaluatorInput:
    Path: "/workspace/robust-rail-evaluator/build/TORS" #../../C++/hello"
    Mode: "EVAL_AND_STORE" #EVAL_AND_STORE or EVAL
    PathLocation: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_known_problems/setting_invalid_endmove"
    PathScenario: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_known_problems/setting_invalid_endmove/scenario_evaluator.json"
    PathPlan: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_known_problems/setting_invalid_endmove/plan.json"
    PlanType: "Solver"
    DepartureDelay: "0"
  ConversionAndStorage:  
    PathEvalResult: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_known_problems/setting_invalid_endmove/Evaluation_Results.txt"
    PathScenarioEval: "/workspace/robust-rail-solver/ServiceSiteScheduling/database/TUSS-Instance-Generator/scenario_settings/setting_known_problems/setting_invalid_endmove"
  DeterministicPlanning:
    LookForSeed: true # if we look for a working seed
    DisplaySeed: true
    Seed: 0